export const EmployCount = [
    { label: "1-20", value: "1-20" },
    { label: "21-50", value: "21-50" },
    { label: "51-100", value: "51-100" },
    { label: "101-500", value: "101-500" },
    { label: "500+", value: "500+" },
]

export const Industries = [
    "Accounting / Auditing",
    "Advertising & Marketing",
    "Agriculture / Forestry / Fishing",
    "Analytics / KPO / Research",
    "Animation & VFX",
    "Architecture / Interior Design",
    "Auto Components",
    "Automobile",
    "Aviation",
    "Banking",
    "Beauty & Personal Care",
    "Beverage",
    "BFSI",
    "Biotechnology",
    "BPM",
    "BPO / Call Centre",
    "Building Material",
    "Chemicals",
    "Clinical Research / Contract Research",
    "Consumer Electronics & Appliances",
    "Consumer, Retail & Hospitality",
    "Content Development / Language",
    "Courier / Logistics",
    "Defence & Aerospace",
    "Design",
    "E-Learning / EdTech",
    "Education",
    "Education / Training",
    "Electrical Equipment",
    "Electronic Components / Semiconductors",
    "Electronics Manufacturing",
    "Emerging Technologies",
    "Engineering & Construction",
    "Events / Live Entertainment",
    "Facility Management Services",
    "Fertilizers / Pesticides / Agro chemicals",
    "Film / Music / Entertainment",
    "Financial Services",
    "FinTech / Payments",
    "Fitness & Wellness",
    "FMCG",
    "Food Processing",
    "Furniture & Furnishing",
    "Gaming",
    "Gems & Jewellery",
    "Government / Public Administration",
    "Hardware & Networking",
    "Healthcare & Life Sciences",
    "Hotels & Restaurants",
    "Import & Export",
    "Industrial Automation",
    "Industrial Equipment / Machinery",
    "Infrastructure, Transport & Real Estate",
    "Insurance",
    "Internet",
    "Investment Banking / Venture Capital / Private Equity",
    "Iron & Steel",
    "IT Services",
    "IT Services & Consulting",
    "Law Enforcement / Security Services",
    "Legal",
    "Management Consulting",
    "Manufacturing & Production",
    "Media, Entertainment & Telecom",
    "Medical Devices & Equipment",
    "Medical Services / Hospital",
    "Metals & Mining",
    "Miscellaneous",
    "NBFC",
    "NGO / Social Services / Industry Associations",
    "Oil & Gas",
    "Packaging & Containers",
    "Petrochemical / Plastics / Rubber",
    "Pharmaceutical & Life Sciences",
    "Ports & Shipping",
    "Power",
    "Printing & Publishing",
    "Professional Services",
    "Pulp & Paper",
    "Railways",
    "Real Estate",
    "Recruitment / Staffing",
    "Retail",
    "Software Product",
    "Sports / Leisure & Recreation",
    "Technology",
    "Telecom / ISP",
    "Textile & Apparel",
    "Travel & Tourism",
    "TV / Radio",
    "Urban Transport",
    "Water Treatment / Waste Management"
];  
